In [ ]:
import torch
print(torch.__version__)


2.5.0+cu121


In [ ]:
scaler = torch.tensor(7)
print(scaler.dtype)
print(scaler.shape)
scaler.ndim
scaler.item()

torch.int64
torch.Size([])


7

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
MATRIX = torch.tensor([[7,8], [9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
print(MATRIX.ndim)
print(MATRIX.shape)
print(MATRIX[1])



2
torch.Size([2, 2])
tensor([ 9, 10])


In [ ]:
tensor = torch.tensor([[[1,2,4],
                        [3,4,5],
                        [6,7,8]]])
tensor

tensor([[[1, 2, 4],
         [3, 4, 5],
         [6, 7, 8]]])

In [ ]:
tensor1 = torch.tensor([[[1,2],[3,4]], [[5,6],[7,8]], [[9,10],[11,12]]])
tensor1

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])

In [ ]:
print(tensor1.ndim)
print(tensor.ndim)
print(tensor1.shape)
print(tensor.shape)



3
3
torch.Size([3, 2, 2])
torch.Size([1, 3, 3])


In [ ]:
print(tensor[0])

tensor([[1, 2, 4],
        [3, 4, 5],
        [6, 7, 8]])


In [ ]:
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.3982, 0.1636, 0.0117, 0.9059],
         [0.2526, 0.6794, 0.7707, 0.4674],
         [0.5450, 0.1261, 0.4264, 0.0801]]])

In [ ]:
random_tensor1 = torch.rand(225, 225, 3)


print(random_tensor1.ndim)
print(random_tensor1.shape)

3
torch.Size([225, 225, 3])


In [ ]:
random_tensor2 = torch.rand(size=(225, 225, 3))

print(random_tensor2.ndim)
print(random_tensor2.shape)

3
torch.Size([225, 225, 3])


In [ ]:
ones = torch.ones(size=(3,4))
ones


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros



tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
one_to_ten = torch.arange(0,11,1)

In [ ]:
torch.zeros_like(one_to_ten)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
new_tensor = torch.tensor([1.7, -99.3, 5], dtype=None, device="cpu", requires_grad=False)
print(new_tensor.dtype)
print(new_tensor.device)
print(new_tensor.requires_grad)


torch.float32
cpu
False


In [ ]:
float_16_tensor = new_tensor.type(torch.float16)
float_16_tensor

tensor([  1.7002, -99.3125,   5.0000], dtype=torch.float16)

In [ ]:
float_16_tensor * new_tensor

tensor([2.8903e+00, 9.8617e+03, 2.5000e+01])

In [ ]:
int_32_tensor = torch.tensor([1,2,3], dtype=torch.int32)
int_32_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
int_32_tensor * new_tensor


tensor([   1.7000, -198.6000,   15.0000])

In [ ]:
some_tensor = torch.rand(3,4)


In [ ]:
print(some_tensor)
print(f" Datatype of tensor: {some_tensor.dtype}")
print(f" Shape of tensor: {some_tensor.shape}")
print(f" Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.5274, 0.5881, 0.4990, 0.2085],
        [0.3625, 0.3847, 0.0722, 0.9109],
        [0.1251, 0.5589, 0.5332, 0.6699]])
 Datatype of tensor: torch.float32
 Shape of tensor: torch.Size([3, 4])
 Device tensor is stored on: cpu


In [ ]:
some_tensor.device

device(type='cpu')

In [ ]:
tensor = torch.tensor([1,2,3])
print(tensor + 10)
print(tensor * 10)
print(tensor - 10)
print(tensor / 10)

tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([-9, -8, -7])
tensor([0.1000, 0.2000, 0.3000])


In [ ]:
print(torch.mul(tensor, 10))
print(torch.add(tensor, 10))
print(torch.sub(tensor, 10))
print(torch.div(tensor, 10))

tensor([10, 20, 30])
tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([0.1000, 0.2000, 0.3000])


In [ ]:
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
print(torch.matmul(tensor, tensor))

tensor(14)


In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
%%time
sum = 0
for i in range(len(tensor)):
  sum += tensor[i] * tensor[i]
print(sum)

tensor(14)
CPU times: user 3.95 ms, sys: 0 ns, total: 3.95 ms
Wall time: 6.96 ms


In [ ]:
%%time
print(torch.matmul(tensor, tensor))

tensor(14)
CPU times: user 849 µs, sys: 0 ns, total: 849 µs
Wall time: 858 µs


In [ ]:
%%time
print(tensor @ tensor)

tensor(14)
CPU times: user 3.05 ms, sys: 928 µs, total: 3.97 ms
Wall time: 7.06 ms


In [ ]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))
torch.matmul(torch.rand(10,32), torch.rand(3,10)).shape

RuntimeError: mat1 and mat2 shapes cannot be multiplied (10x32 and 3x10)

In [ ]:
tensor_a = torch.tensor([[1,2],[2,3],
                         [3, 4], [4,5],
                         [5,6], [6,7]])
tensor_b = torch.tensor([[7,10],[8,11],
                         [9,12], [10,13],
                         [11,14], [12,15]])
torch.mm(tensor_a, tensor_b)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (6x2 and 6x2)

In [ ]:
tensor_a.T

tensor([[1, 2, 3, 4, 5, 6],
        [2, 3, 4, 5, 6, 7]])

In [ ]:
tensor_a

tensor([[1, 2],
        [2, 3],
        [3, 4],
        [4, 5],
        [5, 6],
        [6, 7]])

In [ ]:
 torch.mm(tensor_a.T, tensor_b)

tensor([[217, 280],
        [274, 355]])

In [ ]:
x =torch.arange(0,100,10)

In [ ]:
print(torch.min(x), x.min())
print(torch.max(x), x.max())

tensor(0) tensor(0)
tensor(90) tensor(90)


In [ ]:
x.type(torch.float32).mean(), torch.mean(x.type(torch.float32))

(tensor(45.), tensor(45.))

In [ ]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [ ]:
print(torch.argmin(x), x.argmin())
print(torch.argmax(x), x.argmax())


tensor(0) tensor(0)
tensor(9) tensor(9)


In [ ]:
import torch
x = torch.arange(1, 13)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
x.dtype
x.shape

torch.Size([12])

In [ ]:
x_reshaped = x.reshape(3,4)
x_reshaped

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [ ]:
z= x.view(3,4)
z, x

(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]),
 tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]))

In [ ]:
z[:, 0] = 5
z, x

(tensor([[ 5,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 5, 10, 11, 12]]),
 tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  5, 10, 11, 12]))

In [ ]:
x_stacked = torch.stack([x ,x], dim = -2)
x_stacked

tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  5, 10, 11, 12],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  5, 10, 11, 12]])

In [ ]:
x_reshaped = x.reshape(1,2,6)
x_reshaped

tensor([[[ 5,  2,  3,  4,  5,  6],
         [ 7,  8,  5, 10, 11, 12]]])

In [ ]:
x_squeezed = x_reshaped.squeeze(dim = 0)
x_squeezed.shape

torch.Size([2, 6])

In [ ]:
x_unsqueezed = x_squeezed.unsqueeze(dim = 2)
x_unsqueezed, x_unsqueezed.shape

(tensor([[[ 5],
          [ 2],
          [ 3],
          [ 4],
          [ 5],
          [ 6]],
 
         [[ 7],
          [ 8],
          [ 5],
          [10],
          [11],
          [12]]]),
 torch.Size([2, 6, 1]))

In [ ]:
x_random = torch.randn(223, 224, 3)
x_random = x_random.permute(2, 0, 1)
x_random.shape

torch.Size([3, 223, 224])

In [1]:
import torch
import numpy as np

array = np.arange (1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [3]:
array += 1
array, tensor

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [5]:
tenor = torch.ones(7)
numpy_tensor = tenor.numpy()
tenor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [6]:
random_tensor1 = torch.rand(3,4)
random_tensor2 = torch.rand(3,4)

random_tensor1 == random_tensor2

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [10]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor1 = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor2 = torch.rand(3,4)

random_tensor1 == random_tensor2

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [1]:
!nvidia-smi

Fri Nov 15 09:11:28 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   52C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
import torch
torch.cuda.is_available()

True

In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
torch.cuda.device_count()

1

In [7]:
tensor = torch.tensor([1,2,3], device = "cpu")
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [8]:
tensor_to_gpu =tensor.to(device)
tensor_to_gpu

tensor([1, 2, 3], device='cuda:0')

In [9]:
tensor_to_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [10]:
tensor_on_cpu = tensor_to_gpu.cpu().numpy()
tensor_on_cpu

array([1, 2, 3])